In [1]:
import fix_yahoo_finance as yf
import datetime as dt 
start = dt.datetime(1990, 1, 1)
end = dt.datetime.utcnow()
yf.download('005930.KS', start = start, end = end)

[*********************100%***********************]  1 of 1 downloaded

            Adj Close    Close     High      Low     Open     Volume
Date
2000-01-04       0.09   6110.0   6110.0   5660.0   6000.0   74195000
2000-01-05       0.08   5580.0   6060.0   5520.0   5800.0   74680000
2000-01-06       0.08   5620.0   5780.0   5580.0   5750.0   54390000
2000-01-07       0.08   5540.0   5670.0   5360.0   5560.0   40305000
2000-01-10       0.09   5770.0   5770.0   5580.0   5600.0   46880000
2000-01-11       0.09   5770.0   6100.0   5770.0   5820.0   59745000
2000-01-12       0.08   5720.0   5740.0   5600.0   5610.0   29220000
2000-01-13       0.08   5710.0   5740.0   5560.0   5600.0   41190000
2000-01-14       0.09   5830.0   5880.0   5680.0   5720.0   49375000
2000-01-17       0.09   6100.0   6180.0   5920.0   6000.0   63505000
2000-01-18       0.09   6100.0   6160.0   5980.0   6160.0   45260000
2000-01-19       0.09   5960.0   6040.0   5960.0   6000.0   40205000
2000-01-20       0.09   6040.0   6040.0   5820.0   5860.0   37315000
2000-01-21       0.09   5880.0   5980.0   5880.0   5950.0   32535000
2000-01-24       0.08   5700.0   5900.0   5700.0   5800.0   34355000
2000-01-25       0.08   5440.0   5640.0   5440.0   5520.0   44250000
2000-01-26       0.08   5480.0   5520.0   5410.0   5500.0   29285000
2000-01-27       0.08   5520.0   5620.0   5430.0   5480.0   27900000
2000-01-28       0.09   5820.0   5880.0   5540.0   5640.0   38315000
2000-01-31       0.08   5580.0   5730.0   5560.0   5640.0   39630000
2000-02-01       0.08   5320.0   5680.0   5260.0   5600.0   71470000
2000-02-02       0.08   5250.0   5370.0   5110.0   5220.0   64105000
2000-02-03       0.08   5130.0   5460.0   4970.0   5250.0  142765000
2000-02-04       0.08   5130.0   5130.0   5130.0   5130.0          0
2000-02-07       0.08   5240.0   5330.0   5040.0   5140.0   64140000
2000-02-08       0.08   5430.0   5480.0   5310.0   5340.0   58460000
2000-02-09       0.08   5720.0   5720.0   5480.0   5560.0   51050000
2000-02-10       0.09   5760.0   5880.0   5600.0   5660.0   61845000
2000-02-11       0.08   5700.0   5960.0   5680.0   5960.0   34660000
2000-02-14       0.08   5380.0   5660.0   5340.0   5600.0   44140000
...               ...      ...      ...      ...      ...        ...
2018-12-20   38293.23  38650.0  39100.0  38500.0  38600.0   11937617
2018-12-21   38293.23  38650.0  38650.0  38100.0  38200.0   14947080
2018-12-24   38441.84  38800.0  39050.0  38300.0  38500.0    9729530
2018-12-26   37996.00  38350.0  38750.0  38300.0  38400.0   12707675
2018-12-27   38250.00  38250.0  38800.0  38100.0  38700.0   10510643
2018-12-28   38700.00  38700.0  38900.0  38200.0  38250.0    9900267
2019-01-02   38750.00  38750.0  39400.0  38550.0  39400.0    7847664
2019-01-03   37600.00  37600.0  38550.0  37450.0  38300.0   12471493
2019-01-04   37450.00  37450.0  37600.0  36850.0  37450.0   14108958
2019-01-07   38750.00  38750.0  38900.0  37800.0  38000.0   12748997
2019-01-08   38100.00  38100.0  39200.0  37950.0  38000.0   12756554
2019-01-09   39600.00  39600.0  39600.0  38300.0  38650.0   17452708
2019-01-10   39800.00  39800.0  40150.0  39600.0  40000.0   14731699
2019-01-11   40500.00  40500.0  40550.0  39950.0  40350.0   11661063
2019-01-14   40050.00  40050.0  40700.0  39850.0  40450.0   11984996
2019-01-15   41100.00  41100.0  41100.0  39850.0  40050.0   11492756
2019-01-16   41450.00  41450.0  41450.0  40700.0  41150.0    8491595
2019-01-17   41950.00  41950.0  42100.0  41450.0  41700.0   11736903
2019-01-18   42300.00  42300.0  42400.0  41950.0  42000.0   11029256
2019-01-21   42750.00  42750.0  42750.0  41900.0  42700.0   11355701
2019-01-22   42150.00  42150.0  42850.0  41850.0  42750.0    9964356
2019-01-23   42000.00  42000.0  42250.0  41350.0  41350.0   11071079
2019-01-24   43050.00  43050.0  43100.0  42350.0  43050.0   14747623
2019-01-25   44750.00  44750.0  44750.0  43750.0  44300.0   22789395
2019-01-28   45050.00  45050.0  45500.0  44600.0  45000.0   17998914
2019-01-29   45500.00  45500.0  45500.0  44350.0  45050.0   16215017
2019-01-30   46400.00  46400.0  46400.0  44800.0  44800.0   17505980
2019-01-31   46150.00  46150.0  47050.0  46150.0  46650.0   21621145
2019-02-01   46350.00  46350.0  46950.0  46250.0  46650.0   13832454
2019-05-14   42650.00  42650.0  43100.0  41300.0  41300.0   11539496

[4805 rows x 6 columns]